services:
  - type: web
    name: recipe-api
    runtime: python
    rootDir: api
    branch: main
    autoDeployTrigger: commit
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    preDeployCommand: python -m migrations.run
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /up
